{{ $namespace := .Release.Name }}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ print $namespace "-api-clusterip" }}
  name: {{ print $namespace "-api-clusterip" }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ print $namespace "-api" }}
  type: ClusterIP
status:
  loadBalancer: {}
