{{ $namespace := .Release.Name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ print $namespace "-ui" }}
  name: {{ print $namespace "-ui" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ print $namespace "-ui" }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ print $namespace "-ui" }}
    spec:
      containers:
      - image: {{ print $.Values.UI.Image ":"  $.Values.UI.tag }}
        name: {{ print $namespace "-ui" }}
        resources: {}
        ports:
        - containerPort: 5173
status: {}
